export type Product = { id: number; slug: string; name: string; category: string; duration: string; price: number; description: string; icon: string; image?: string; featured?: boolean; details: string[] };
// EDIT PRODUCTS HERE: change name, price, description, category, duration, or image path.
// Put product images in public/products/ and set image to '/products/your-image.jpg'.
export const products: Product[] = [
  { id: 1, slug: 'gemini-ai-pro', name: 'Gemini AI Pro', category: 'AI Tools', duration: 'Subscription', price: 450, description: 'AI tools for writing, research and productivity.', icon: '✦', featured: true, details: ['Useful AI features for everyday productivity.', 'Availability and duration should be confirmed before ordering.', 'Digital delivery details are confirmed after order review.'] },
  { id: 2, slug: 'chatgpt', name: 'ChatGPT', category: 'AI Tools', duration: 'Subscription', price: 500, description: 'AI assistant access options, subject to eligibility.', icon: '◎', featured: true, details: ['AI assistance for writing, learning and brainstorming.', 'Plan eligibility and terms may vary.', 'Confirm the exact plan before purchase.'] },
  { id: 3, slug: 'canva-pro', name: 'Canva Pro', category: 'Design', duration: 'Subscription', price: 180, description: 'Design assets and creative workflow tools.', icon: '✿', featured: true, details: ['Design tools for social posts and creative projects.', 'Duration and access method are confirmed before ordering.', 'Use the service according to its official terms.'] },
  { id: 4, slug: 'capcut-pro', name: 'CapCut Pro', category: 'Video', duration: 'Subscription', price: 220, description: 'Video editing features for creators.', icon: '◈', details: ['Video editing features for content creators.', 'Availability may depend on region and plan.', 'Confirm delivery details before ordering.'] },
  { id: 5, slug: 'microsoft-365', name: 'Microsoft 365', category: 'Productivity', duration: 'License / plan', price: 350, description: 'Productivity tools for eligible accounts.', icon: '▦', details: ['Productivity apps and services.', 'License type and duration should be confirmed.', 'Only valid, authorized licenses should be sold.'] },
  { id: 6, slug: 'figma', name: 'Figma', category: 'Design', duration: 'Plan varies', price: 250, description: 'Collaborative interface design tools.', icon: '◉', details: ['Collaborative design and prototyping.', 'Plan eligibility may vary.', 'Confirm the exact plan before ordering.'] },
  { id: 7, slug: 'claude', name: 'Claude', category: 'AI Tools', duration: 'Plan varies', price: 300, description: 'AI assistance options, depending on availability.', icon: '✳', details: ['AI assistance for writing and analysis.', 'Availability and plan terms may vary.', 'Confirm plan details before ordering.'] },
  { id: 8, slug: 'creative-tools-bundle', name: 'Creative Tools Bundle', category: 'Bundles', duration: 'Bundle', price: 399, description: 'A curated collection of digital productivity tools.', icon: '⚡', details: ['A bundle of creative and productivity tools.', 'Included services should be listed clearly before sale.', 'Confirm what is included before ordering.'] }
];
export const categories = ['All', 'AI Tools', 'Design', 'Video', 'Productivity', 'Bundles'];
export const getProduct = (id: string | number) => products.find(p => String(p.id) === String(id) || p.slug === String(id));
